# Generated by Django 5.1.4 on 2024-12-29 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemeindewappen_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wappen',
            old_name='beschreibung',
            new_name='blasonierung',
        ),
        migrations.AddField(
            model_name='wappen',
            name='bbox',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wappen',
            name='koordinaten',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Tinktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('farbe', models.CharField(max_length=20)),
                ('textfarbe', models.CharField(default='#FFFFFF', max_length=20)),
                ('wappen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinkturen', to='gemeindewappen_website.wappen')),
            ],
        ),
    ]
