# Generated by Django 5.1.4 on 2024-12-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemeindewappen_website', '0002_rename_beschreibung_wappen_blasonierung_wappen_bbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landkreis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
