# Generated by Django 5.1.4 on 2024-12-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemeindewappen_website', '0003_landkreis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landkreis',
            options={},
        ),
    ]
